packages:
  - '.'

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  core-js: true
  nodemon: true
  prisma: true
  sharp: true
  unrs-resolver: true
