import type { ForestSeason } from "./themes";

export type SeasonGameType =
  | "flip"
  | "speak"
  | "memory"
  | "ordering"
  | "scramble"
  | "menu"
  | "topic";

export type GameSeasonTheme = {
  storyEmoji: string;
  storyTitle: string;
  storySubtitle: string;
  cardBack: string;
  panel: string;
  panelBorder: string;
  panelShadow: string;
  storyBadge: string;
  heading: string;
  subtext: string;
  label: string;
  statBg: string;
  statDivider: string;
  hero: string;
  cardHidden: string;
  cardRevealed: string;
  cardMatched: string;
  tile: string;
  tileActive: string;
  dropZone: string;
  input: string;
  primaryBtn: string;
  secondaryBtn: string;
  progressTrack: string;
  progressFill: string;
  statusInfo: string;
  statusSuccess: string;
  menuOverlay: string;
  menuRing: string;
  topicOverlay: string;
  topicBadge: string;
};

type StoryDef = Pick<
  GameSeasonTheme,
  "storyEmoji" | "storyTitle" | "storySubtitle" | "cardBack"
>;

const STORIES: Record<ForestSeason, Record<SeasonGameType, StoryDef>> = {
  spring: {
    flip: {
      storyEmoji: "🌸",
      storyTitle: "Thẻ hoa anh đào",
      storySubtitle: "Lật từng cánh hoa để khám phá từ vựng trong vườn xuân.",
      cardBack: "🌸",
    },
    speak: {
      storyEmoji: "🐦",
      storyTitle: "Chim sơn ca dạy nói",
      storySubtitle: "Học phát âm cùng tiếng chim trong khu rừng nở hoa.",
      cardBack: "🎵",
    },
    memory: {
      storyEmoji: "🦋",
      storyTitle: "Cánh bướm đôi",
      storySubtitle: "Ghép cặp từ như ghép đôi cánh bướm bay giữa đồng cỏ.",
      cardBack: "🦋",
    },
    ordering: {
      storyEmoji: "🌷",
      storyTitle: "Dãy hoa A-Z",
      storySubtitle: "Xếp từ theo thứ tự như hàng hoa nở dần từ sáng đến trưa.",
      cardBack: "🌷",
    },
    scramble: {
      storyEmoji: "🍃",
      storyTitle: "Lá xanh xáo trộn",
      storySubtitle: "Sắp xếp chữ cái như ghép lại những chiếc lá sau cơn gió xuân.",
      cardBack: "🍃",
    },
    menu: {
      storyEmoji: "📖",
      storyTitle: "Cuốn truyện xuân",
      storySubtitle: "Chọn cuộc phiêu lưu học tập trong khu rừng cổ tích đang nở hoa.",
      cardBack: "✨",
    },
    topic: {
      storyEmoji: "🗺️",
      storyTitle: "Bản đồ khu vườn",
      storySubtitle: "Chọn lối đi trong khu vườn phép thuật để bắt đầu hành trình.",
      cardBack: "🌼",
    },
  },
  summer: {
    flip: {
      storyEmoji: "☀️",
      storyTitle: "Thẻ nắng hạ",
      storySubtitle: "Lật thẻ dưới ánh nắng vàng — mỗi từ là một tia sáng mới.",
      cardBack: "☀️",
    },
    speak: {
      storyEmoji: "🌊",
      storyTitle: "Tiếng sóng dạy nói",
      storySubtitle: "Luyện phát âm với nhịp sóng và gió biển mùa hè.",
      cardBack: "🐚",
    },
    memory: {
      storyEmoji: "🐠",
      storyTitle: "Cá đôi nhiệt đới",
      storySubtitle: "Tìm cặp từ như tìm đôi cá bơi giữa rạn san hô.",
      cardBack: "🐠",
    },
    ordering: {
      storyEmoji: "🏝️",
      storyTitle: "Đảo chữ cái",
      storySubtitle: "Sắp xếp từ trên những hòn đảo nhỏ giữa biển xanh.",
      cardBack: "🏝️",
    },
    scramble: {
      storyEmoji: "🍉",
      storyTitle: "Trái cây xáo trộn",
      storySubtitle: "Ghép chữ như ghép miếng trái cây mát lạnh mùa hè.",
      cardBack: "🍉",
    },
    menu: {
      storyEmoji: "⛵",
      storyTitle: "Hành trình mùa hè",
      storySubtitle: "Chọn game và lao vào cuộc phiêu lưu dưới trời hè rực rỡ.",
      cardBack: "🌴",
    },
    topic: {
      storyEmoji: "🧭",
      storyTitle: "La bàn mùa hè",
      storySubtitle: "Chọn chủ đề để khám phá hòn đảo tri thức của riêng bạn.",
      cardBack: "🌊",
    },
  },
  autumn: {
    flip: {
      storyEmoji: "🍂",
      storyTitle: "Thẻ lá vàng",
      storySubtitle: "Lật những chiếc lá để tìm từ vựng ẩn giấu trong rừng thu.",
      cardBack: "🍂",
    },
    speak: {
      storyEmoji: "🦉",
      storyTitle: "Cú thu dạy nói",
      storySubtitle: "Phát âm chuẩn cùng chú cú khôn ngoan trong đêm sương thu.",
      cardBack: "🦉",
    },
    memory: {
      storyEmoji: "🌰",
      storyTitle: "Hạt dẻ đôi",
      storySubtitle: "Ghép cặp từ như thu thập hạt dẻ dưới gốc cây vàng.",
      cardBack: "🌰",
    },
    ordering: {
      storyEmoji: "🎃",
      storyTitle: "Bí ngô chữ cái",
      storySubtitle: "Xếp từ theo thứ tự trên con đường lát lá cam.",
      cardBack: "🎃",
    },
    scramble: {
      storyEmoji: "🍁",
      storyTitle: "Lá rơi xáo trộn",
      storySubtitle: "Sắp xếp chữ cái như gom lá rơi thành từ hoàn chỉnh.",
      cardBack: "🍁",
    },
    menu: {
      storyEmoji: "🏡",
      storyTitle: "Cottage mùa thu",
      storySubtitle: "Chọn game trong ngôi nhà gỗ ấm áp giữa rừng lá đỏ.",
      cardBack: "🕯️",
    },
    topic: {
      storyEmoji: "🛤️",
      storyTitle: "Lối mòn thu",
      storySubtitle: "Chọn topic để bước vào con đường vàng trong khu rừng thu.",
      cardBack: "🍄",
    },
  },
  winter: {
    flip: {
      storyEmoji: "❄️",
      storyTitle: "Thẻ băng giá",
      storySubtitle: "Lật thẻ pha lê để mở khóa từ vựng trong lâu đài tuyết.",
      cardBack: "❄️",
    },
    speak: {
      storyEmoji: "🔔",
      storyTitle: "Chuông băng dạy nói",
      storySubtitle: "Luyện phát âm trong không khí yên tĩnh của đêm đông.",
      cardBack: "🔔",
    },
    memory: {
      storyEmoji: "⛄",
      storyTitle: "Người tuyết đôi",
      storySubtitle: "Ghép cặp từ như ghép đôi mũ len trên tuyết trắng.",
      cardBack: "⛄",
    },
    ordering: {
      storyEmoji: "🎁",
      storyTitle: "Hộp quà chữ cái",
      storySubtitle: "Xếp từ như sắp xếp những món quà dưới cây thông.",
      cardBack: "🎁",
    },
    scramble: {
      storyEmoji: "🧊",
      storyTitle: "Pha lê xáo trộn",
      storySubtitle: "Ghép chữ cái như ghép mảnh băng thành từ hoàn chỉnh.",
      cardBack: "🧊",
    },
    menu: {
      storyEmoji: "🏰",
      storyTitle: "Lâu đài tuyết",
      storySubtitle: "Chọn game trong lâu đài cổ tích phủ tuyết trắng.",
      cardBack: "✨",
    },
    topic: {
      storyEmoji: "🚪",
      storyTitle: "Cánh cổng băng",
      storySubtitle: "Chọn topic để bước qua cổng băng vào thế giới từ vựng.",
      cardBack: "🌟",
    },
  },
};

/** Palette per season × game — full theme colors */
const PALETTES: Record<ForestSeason, Record<SeasonGameType, Omit<GameSeasonTheme, keyof StoryDef>>> = {
  spring: {
    flip: {
      panel: "bg-white/90 backdrop-blur-md",
      panelBorder: "border-sky-200/80",
      panelShadow: "shadow-xl shadow-pink-200/30",
      storyBadge: "bg-gradient-to-r from-pink-100 to-sky-100 text-sky-900 border-pink-200/60",
      heading: "text-sky-900",
      subtext: "text-sky-700",
      label: "text-sky-600",
      statBg: "bg-white/80",
      statDivider: "divide-sky-100",
      hero: "bg-gradient-to-br from-sky-400 via-pink-300 to-blue-500",
      cardHidden: "border-pink-200 bg-gradient-to-br from-sky-100 via-pink-50 to-blue-200 hover:border-pink-300 hover:shadow-lg hover:-translate-y-1",
      cardRevealed: "border-sky-300 bg-sky-50",
      cardMatched: "bg-emerald-100 border-emerald-400",
      tile: "bg-sky-100 border-sky-300 text-sky-900 hover:bg-sky-200",
      tileActive: "bg-sky-500 text-white border-sky-600",
      dropZone: "border-dashed border-pink-300 bg-pink-50/50",
      input: "border-pink-300 focus:border-sky-500 focus:ring-sky-200",
      primaryBtn: "bg-gradient-to-r from-sky-500 via-pink-400 to-blue-600 hover:shadow-xl hover:-translate-y-0.5",
      secondaryBtn: "border-2 border-sky-400 text-sky-700 bg-white hover:bg-sky-50",
      progressTrack: "bg-pink-100",
      progressFill: "bg-gradient-to-r from-sky-400 to-pink-400",
      statusInfo: "bg-sky-50 text-sky-800",
      statusSuccess: "bg-emerald-100 text-emerald-800",
      menuOverlay: "ring-pink-300/60 shadow-pink-200/40",
      menuRing: "ring-pink-200/80",
      topicOverlay: "bg-pink-900/25",
      topicBadge: "border-pink-200/50 bg-white/80 text-pink-900",
    },
    speak: {
      panel: "bg-white/90 backdrop-blur-md",
      panelBorder: "border-emerald-200/80",
      panelShadow: "shadow-xl shadow-emerald-200/30",
      storyBadge: "bg-gradient-to-r from-emerald-100 to-pink-100 text-emerald-900 border-emerald-200/60",
      heading: "text-emerald-900",
      subtext: "text-emerald-700",
      label: "text-emerald-600",
      statBg: "bg-white/80",
      statDivider: "divide-emerald-100",
      hero: "bg-gradient-to-br from-emerald-400 via-green-300 to-teal-500",
      cardHidden: "border-emerald-200 bg-gradient-to-br from-green-100 to-emerald-200",
      cardRevealed: "border-emerald-400 bg-emerald-50",
      cardMatched: "bg-green-200 border-green-500",
      tile: "bg-emerald-100 border-emerald-300 text-emerald-900",
      tileActive: "bg-emerald-600 text-white",
      dropZone: "border-emerald-300 bg-emerald-50/50",
      input: "border-emerald-300 focus:border-emerald-500 focus:ring-emerald-200",
      primaryBtn: "bg-gradient-to-r from-emerald-500 to-teal-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-emerald-400 text-emerald-700 bg-white hover:bg-emerald-50",
      progressTrack: "bg-emerald-100",
      progressFill: "bg-gradient-to-r from-emerald-400 to-green-500",
      statusInfo: "bg-emerald-50 text-emerald-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "ring-emerald-300/60",
      menuRing: "ring-emerald-200/80",
      topicOverlay: "bg-emerald-900/20",
      topicBadge: "border-emerald-200/50 bg-white/80 text-emerald-900",
    },
    memory: {
      panel: "bg-white/90 backdrop-blur-md",
      panelBorder: "border-orange-200/80",
      panelShadow: "shadow-xl shadow-orange-200/25",
      storyBadge: "bg-gradient-to-r from-orange-100 to-pink-100 text-orange-900 border-orange-200/60",
      heading: "text-orange-900",
      subtext: "text-orange-700",
      label: "text-orange-600",
      statBg: "bg-white/80",
      statDivider: "divide-orange-100",
      hero: "bg-gradient-to-br from-orange-400 via-amber-300 to-rose-400",
      cardHidden: "border-orange-200 bg-gradient-to-br from-orange-100 to-pink-100 hover:border-orange-400 hover:-translate-y-1",
      cardRevealed: "border-orange-400 bg-white shadow-lg",
      cardMatched: "bg-green-200 border-green-500",
      tile: "bg-orange-100 border-orange-300 text-orange-900",
      tileActive: "bg-orange-500 text-white",
      dropZone: "border-orange-300 bg-orange-50/50",
      input: "border-orange-300 focus:border-orange-500",
      primaryBtn: "bg-gradient-to-r from-orange-500 to-rose-500 hover:shadow-xl",
      secondaryBtn: "border-2 border-orange-400 text-orange-700 bg-white",
      progressTrack: "bg-orange-100",
      progressFill: "bg-gradient-to-r from-orange-400 to-pink-400",
      statusInfo: "bg-orange-50 text-orange-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "ring-orange-300/60",
      menuRing: "ring-orange-200/80",
      topicOverlay: "bg-orange-900/20",
      topicBadge: "border-orange-200/50 bg-white/80 text-orange-900",
    },
    ordering: {
      panel: "bg-white/90 backdrop-blur-md",
      panelBorder: "border-rose-200/80",
      panelShadow: "shadow-xl shadow-rose-200/25",
      storyBadge: "bg-gradient-to-r from-rose-100 to-pink-100 text-rose-900 border-rose-200/60",
      heading: "text-rose-900",
      subtext: "text-rose-700",
      label: "text-rose-600",
      statBg: "bg-white/80",
      statDivider: "divide-rose-100",
      hero: "bg-gradient-to-br from-rose-400 via-red-300 to-pink-500",
      cardHidden: "border-rose-200 bg-rose-100",
      cardRevealed: "border-rose-400 bg-rose-50",
      cardMatched: "bg-green-200 border-green-500",
      tile: "bg-rose-100 border-rose-300 text-rose-900 hover:bg-rose-200",
      tileActive: "bg-rose-500 text-white border-rose-600",
      dropZone: "border-dashed border-rose-300 bg-rose-50/60",
      input: "border-rose-300 focus:border-rose-500",
      primaryBtn: "bg-gradient-to-r from-rose-500 to-red-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-rose-400 text-rose-700 bg-white",
      progressTrack: "bg-rose-100",
      progressFill: "bg-gradient-to-r from-rose-400 to-red-500",
      statusInfo: "bg-rose-50 text-rose-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "ring-rose-300/60",
      menuRing: "ring-rose-200/80",
      topicOverlay: "bg-rose-900/20",
      topicBadge: "border-rose-200/50 bg-white/80 text-rose-900",
    },
    scramble: {
      panel: "bg-white/90 backdrop-blur-md",
      panelBorder: "border-fuchsia-200/80",
      panelShadow: "shadow-xl shadow-fuchsia-200/30",
      storyBadge: "bg-gradient-to-r from-fuchsia-100 to-pink-100 text-fuchsia-900 border-fuchsia-200/60",
      heading: "text-fuchsia-900",
      subtext: "text-fuchsia-700",
      label: "text-fuchsia-600",
      statBg: "bg-white/80",
      statDivider: "divide-fuchsia-100",
      hero: "bg-gradient-to-br from-fuchsia-500 via-pink-400 to-rose-500",
      cardHidden: "border-fuchsia-200 bg-fuchsia-100",
      cardRevealed: "border-fuchsia-400 bg-fuchsia-50",
      cardMatched: "bg-green-200 border-green-500",
      tile: "bg-fuchsia-100 border-fuchsia-300 text-fuchsia-900",
      tileActive: "bg-fuchsia-600 text-white",
      dropZone: "border-fuchsia-300 bg-fuchsia-50/50",
      input: "border-fuchsia-300 focus:border-fuchsia-500 focus:ring-fuchsia-200",
      primaryBtn: "bg-gradient-to-r from-fuchsia-500 to-pink-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-fuchsia-400 text-fuchsia-700 bg-white",
      progressTrack: "bg-fuchsia-100",
      progressFill: "bg-gradient-to-r from-fuchsia-400 to-pink-500",
      statusInfo: "bg-fuchsia-50 text-fuchsia-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "ring-fuchsia-300/60",
      menuRing: "ring-fuchsia-200/80",
      topicOverlay: "bg-fuchsia-900/20",
      topicBadge: "border-fuchsia-200/50 bg-white/80 text-fuchsia-900",
    },
    menu: {
      panel: "bg-white/85 backdrop-blur-sm",
      panelBorder: "border-pink-200/60",
      panelShadow: "shadow-pink-200/20",
      storyBadge: "bg-pink-100 text-pink-900 border-pink-200",
      heading: "text-blue-900",
      subtext: "text-slate-700",
      label: "text-pink-600",
      statBg: "bg-white/80",
      statDivider: "divide-pink-100",
      hero: "bg-gradient-to-br from-pink-200 to-sky-200",
      cardHidden: "",
      cardRevealed: "",
      cardMatched: "",
      tile: "",
      tileActive: "",
      dropZone: "",
      input: "",
      primaryBtn: "",
      secondaryBtn: "",
      progressTrack: "bg-pink-100",
      progressFill: "bg-pink-400",
      statusInfo: "bg-pink-50 text-pink-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-pink-300/30",
      menuRing: "ring-pink-300/70",
      topicOverlay: "bg-pink-900/15",
      topicBadge: "border-pink-200 bg-white/70",
    },
    topic: {
      panel: "bg-white/85 backdrop-blur-sm",
      panelBorder: "border-sky-200/60",
      panelShadow: "shadow-sky-200/20",
      storyBadge: "bg-sky-100 text-sky-900 border-sky-200",
      heading: "text-blue-900",
      subtext: "text-slate-700",
      label: "text-sky-600",
      statBg: "bg-white/80",
      statDivider: "divide-sky-100",
      hero: "bg-gradient-to-br from-sky-200 to-pink-200",
      cardHidden: "",
      cardRevealed: "",
      cardMatched: "",
      tile: "",
      tileActive: "",
      dropZone: "",
      input: "",
      primaryBtn: "bg-sky-500 text-white",
      secondaryBtn: "border-sky-400 text-sky-700",
      progressTrack: "bg-sky-100",
      progressFill: "bg-sky-400",
      statusInfo: "bg-sky-50 text-sky-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-sky-300/30",
      menuRing: "ring-sky-300/70",
      topicOverlay: "bg-sky-900/30",
      topicBadge: "border-white/40 bg-white/75 text-sky-900",
    },
  },
  summer: {
    flip: {
      panel: "bg-white/88 backdrop-blur-md",
      panelBorder: "border-cyan-200/80",
      panelShadow: "shadow-xl shadow-cyan-200/35",
      storyBadge: "bg-gradient-to-r from-cyan-100 to-yellow-100 text-cyan-900 border-cyan-200/60",
      heading: "text-cyan-900",
      subtext: "text-cyan-700",
      label: "text-cyan-600",
      statBg: "bg-white/85",
      statDivider: "divide-cyan-100",
      hero: "bg-gradient-to-br from-cyan-400 via-sky-400 to-blue-600",
      cardHidden: "border-cyan-200 bg-gradient-to-br from-cyan-100 via-sky-200 to-blue-300 hover:border-yellow-300 hover:-translate-y-1 hover:shadow-lg",
      cardRevealed: "border-cyan-400 bg-cyan-50",
      cardMatched: "bg-lime-200 border-lime-500",
      tile: "bg-cyan-100 border-cyan-300 text-cyan-900",
      tileActive: "bg-cyan-600 text-white",
      dropZone: "border-cyan-300 bg-cyan-50/50",
      input: "border-cyan-300 focus:border-cyan-500",
      primaryBtn: "bg-gradient-to-r from-cyan-500 via-sky-500 to-blue-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-cyan-400 text-cyan-700 bg-white hover:bg-cyan-50",
      progressTrack: "bg-cyan-100",
      progressFill: "bg-gradient-to-r from-cyan-400 to-yellow-400",
      statusInfo: "bg-cyan-50 text-cyan-900",
      statusSuccess: "bg-lime-100 text-lime-800",
      menuOverlay: "shadow-cyan-300/40",
      menuRing: "ring-yellow-300/70",
      topicOverlay: "bg-cyan-900/25",
      topicBadge: "border-cyan-200/50 bg-white/80 text-cyan-900",
    },
    speak: {
      panel: "bg-white/88 backdrop-blur-md",
      panelBorder: "border-lime-200/80",
      panelShadow: "shadow-xl shadow-lime-200/30",
      storyBadge: "bg-gradient-to-r from-lime-100 to-teal-100 text-lime-900 border-lime-200/60",
      heading: "text-lime-900",
      subtext: "text-lime-800",
      label: "text-lime-700",
      statBg: "bg-white/85",
      statDivider: "divide-lime-100",
      hero: "bg-gradient-to-br from-lime-500 via-green-400 to-teal-600",
      cardHidden: "border-lime-200 bg-lime-100",
      cardRevealed: "border-lime-400 bg-lime-50",
      cardMatched: "bg-green-200 border-green-500",
      tile: "bg-lime-100 border-lime-300 text-lime-900",
      tileActive: "bg-lime-600 text-white",
      dropZone: "border-lime-300 bg-lime-50/50",
      input: "border-lime-300 focus:border-lime-500",
      primaryBtn: "bg-gradient-to-r from-lime-500 to-teal-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-lime-500 text-lime-800 bg-white",
      progressTrack: "bg-lime-100",
      progressFill: "bg-gradient-to-r from-lime-400 to-teal-500",
      statusInfo: "bg-lime-50 text-lime-900",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-lime-300/40",
      menuRing: "ring-lime-300/70",
      topicOverlay: "bg-lime-900/20",
      topicBadge: "border-lime-200/50 bg-white/80 text-lime-900",
    },
    memory: {
      panel: "bg-white/88 backdrop-blur-md",
      panelBorder: "border-amber-200/80",
      panelShadow: "shadow-xl shadow-amber-200/35",
      storyBadge: "bg-gradient-to-r from-amber-100 to-orange-100 text-amber-900 border-amber-200/60",
      heading: "text-amber-900",
      subtext: "text-amber-800",
      label: "text-amber-700",
      statBg: "bg-white/85",
      statDivider: "divide-amber-100",
      hero: "bg-gradient-to-br from-amber-400 via-orange-400 to-red-400",
      cardHidden: "border-amber-200 bg-gradient-to-br from-amber-100 to-orange-200 hover:border-amber-400 hover:-translate-y-1",
      cardRevealed: "border-amber-500 bg-white shadow-lg",
      cardMatched: "bg-green-200 border-green-500",
      tile: "bg-amber-100 border-amber-300 text-amber-900",
      tileActive: "bg-amber-500 text-white",
      dropZone: "border-amber-300 bg-amber-50/50",
      input: "border-amber-300 focus:border-amber-500",
      primaryBtn: "bg-gradient-to-r from-amber-500 to-orange-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-amber-400 text-amber-800 bg-white",
      progressTrack: "bg-amber-100",
      progressFill: "bg-gradient-to-r from-amber-400 to-orange-500",
      statusInfo: "bg-amber-50 text-amber-900",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-amber-300/40",
      menuRing: "ring-amber-300/70",
      topicOverlay: "bg-amber-900/25",
      topicBadge: "border-amber-200/50 bg-white/80 text-amber-900",
    },
    ordering: {
      panel: "bg-white/88 backdrop-blur-md",
      panelBorder: "border-red-200/80",
      panelShadow: "shadow-xl shadow-red-200/25",
      storyBadge: "bg-gradient-to-r from-red-100 to-orange-100 text-red-900 border-red-200/60",
      heading: "text-red-900",
      subtext: "text-red-700",
      label: "text-red-600",
      statBg: "bg-white/85",
      statDivider: "divide-red-100",
      hero: "bg-gradient-to-br from-red-500 via-orange-400 to-amber-500",
      cardHidden: "border-red-200 bg-red-100",
      cardRevealed: "border-red-400 bg-red-50",
      cardMatched: "bg-green-200 border-green-500",
      tile: "bg-red-100 border-red-300 text-red-900 hover:bg-red-200",
      tileActive: "bg-red-600 text-white",
      dropZone: "border-dashed border-red-300 bg-red-50/60",
      input: "border-red-300 focus:border-red-500",
      primaryBtn: "bg-gradient-to-r from-red-500 to-orange-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-red-400 text-red-700 bg-white",
      progressTrack: "bg-red-100",
      progressFill: "bg-gradient-to-r from-red-400 to-orange-500",
      statusInfo: "bg-red-50 text-red-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-red-300/35",
      menuRing: "ring-red-300/70",
      topicOverlay: "bg-red-900/25",
      topicBadge: "border-red-200/50 bg-white/80 text-red-900",
    },
    scramble: {
      panel: "bg-white/88 backdrop-blur-md",
      panelBorder: "border-pink-200/80",
      panelShadow: "shadow-xl shadow-pink-200/35",
      storyBadge: "bg-gradient-to-r from-pink-100 to-rose-100 text-pink-900 border-pink-200/60",
      heading: "text-pink-900",
      subtext: "text-pink-700",
      label: "text-pink-600",
      statBg: "bg-white/85",
      statDivider: "divide-pink-100",
      hero: "bg-gradient-to-br from-pink-500 via-rose-400 to-orange-400",
      cardHidden: "border-pink-200 bg-pink-100",
      cardRevealed: "border-pink-400 bg-pink-50",
      cardMatched: "bg-green-200 border-green-500",
      tile: "bg-pink-100 border-pink-300 text-pink-900",
      tileActive: "bg-pink-600 text-white",
      dropZone: "border-pink-300 bg-pink-50/50",
      input: "border-pink-300 focus:border-pink-500 focus:ring-pink-200",
      primaryBtn: "bg-gradient-to-r from-pink-500 to-rose-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-pink-400 text-pink-700 bg-white",
      progressTrack: "bg-pink-100",
      progressFill: "bg-gradient-to-r from-pink-400 to-rose-500",
      statusInfo: "bg-pink-50 text-pink-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-pink-300/40",
      menuRing: "ring-pink-300/70",
      topicOverlay: "bg-pink-900/25",
      topicBadge: "border-pink-200/50 bg-white/80 text-pink-900",
    },
    menu: {
      panel: "bg-white/85 backdrop-blur-sm",
      panelBorder: "border-cyan-200/60",
      panelShadow: "shadow-cyan-200/25",
      storyBadge: "bg-cyan-100 text-cyan-900 border-cyan-200",
      heading: "text-cyan-900",
      subtext: "text-slate-700",
      label: "text-cyan-600",
      statBg: "bg-white/80",
      statDivider: "divide-cyan-100",
      hero: "bg-gradient-to-br from-cyan-200 to-yellow-200",
      cardHidden: "",
      cardRevealed: "",
      cardMatched: "",
      tile: "",
      tileActive: "",
      dropZone: "",
      input: "",
      primaryBtn: "",
      secondaryBtn: "",
      progressTrack: "bg-cyan-100",
      progressFill: "bg-cyan-400",
      statusInfo: "bg-cyan-50 text-cyan-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-cyan-300/35",
      menuRing: "ring-yellow-300/80",
      topicOverlay: "bg-cyan-900/20",
      topicBadge: "border-cyan-200 bg-white/70",
    },
    topic: {
      panel: "bg-white/85 backdrop-blur-sm",
      panelBorder: "border-teal-200/60",
      panelShadow: "shadow-teal-200/25",
      storyBadge: "bg-teal-100 text-teal-900 border-teal-200",
      heading: "text-teal-900",
      subtext: "text-slate-700",
      label: "text-teal-600",
      statBg: "bg-white/80",
      statDivider: "divide-teal-100",
      hero: "bg-gradient-to-br from-teal-200 to-cyan-200",
      cardHidden: "",
      cardRevealed: "",
      cardMatched: "",
      tile: "",
      tileActive: "",
      dropZone: "",
      input: "",
      primaryBtn: "bg-teal-500 text-white",
      secondaryBtn: "border-teal-400 text-teal-700",
      progressTrack: "bg-teal-100",
      progressFill: "bg-teal-400",
      statusInfo: "bg-teal-50 text-teal-800",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-teal-300/35",
      menuRing: "ring-teal-300/80",
      topicOverlay: "bg-teal-900/35",
      topicBadge: "border-white/40 bg-white/75 text-teal-900",
    },
  },
  autumn: {
    flip: {
      panel: "bg-[#FFF8F0]/92 backdrop-blur-md",
      panelBorder: "border-amber-200/80",
      panelShadow: "shadow-xl shadow-amber-300/30",
      storyBadge: "bg-gradient-to-r from-amber-100 to-orange-100 text-amber-950 border-amber-300/60",
      heading: "text-amber-950",
      subtext: "text-amber-800",
      label: "text-amber-700",
      statBg: "bg-[#FFF8F0]/90",
      statDivider: "divide-amber-200",
      hero: "bg-gradient-to-br from-amber-500 via-orange-400 to-amber-700",
      cardHidden: "border-amber-300 bg-gradient-to-br from-amber-100 via-orange-100 to-yellow-200 hover:border-orange-400 hover:-translate-y-1",
      cardRevealed: "border-amber-500 bg-amber-50",
      cardMatched: "bg-green-200 border-green-600",
      tile: "bg-amber-100 border-amber-400 text-amber-950",
      tileActive: "bg-amber-600 text-white",
      dropZone: "border-amber-400 bg-amber-50/60",
      input: "border-amber-400 focus:border-amber-600",
      primaryBtn: "bg-gradient-to-r from-amber-600 via-orange-500 to-amber-800 hover:shadow-xl",
      secondaryBtn: "border-2 border-amber-500 text-amber-800 bg-[#FFF8F0] hover:bg-amber-50",
      progressTrack: "bg-amber-200",
      progressFill: "bg-gradient-to-r from-amber-500 to-orange-600",
      statusInfo: "bg-amber-100 text-amber-900",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-amber-400/35",
      menuRing: "ring-amber-400/70",
      topicOverlay: "bg-amber-950/35",
      topicBadge: "border-amber-300/50 bg-[#FFF8F0]/85 text-amber-950",
    },
    speak: {
      panel: "bg-[#FFF8F0]/92 backdrop-blur-md",
      panelBorder: "border-emerald-300/70",
      panelShadow: "shadow-xl shadow-emerald-300/25",
      storyBadge: "bg-gradient-to-r from-emerald-100 to-amber-100 text-emerald-950 border-emerald-300/60",
      heading: "text-emerald-950",
      subtext: "text-emerald-800",
      label: "text-emerald-700",
      statBg: "bg-[#FFF8F0]/90",
      statDivider: "divide-emerald-200",
      hero: "bg-gradient-to-br from-emerald-600 via-green-500 to-amber-700",
      cardHidden: "border-emerald-300 bg-emerald-100",
      cardRevealed: "border-emerald-500 bg-emerald-50",
      cardMatched: "bg-green-200 border-green-600",
      tile: "bg-emerald-100 border-emerald-400 text-emerald-950",
      tileActive: "bg-emerald-700 text-white",
      dropZone: "border-emerald-400 bg-emerald-50/50",
      input: "border-emerald-400 focus:border-emerald-600",
      primaryBtn: "bg-gradient-to-r from-emerald-600 to-amber-700 hover:shadow-xl",
      secondaryBtn: "border-2 border-emerald-500 text-emerald-800 bg-[#FFF8F0]",
      progressTrack: "bg-emerald-200",
      progressFill: "bg-gradient-to-r from-emerald-500 to-amber-600",
      statusInfo: "bg-emerald-100 text-emerald-900",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-emerald-400/30",
      menuRing: "ring-emerald-400/70",
      topicOverlay: "bg-emerald-950/30",
      topicBadge: "border-emerald-300/50 bg-[#FFF8F0]/85 text-emerald-950",
    },
    memory: {
      panel: "bg-[#FFF8F0]/92 backdrop-blur-md",
      panelBorder: "border-orange-300/70",
      panelShadow: "shadow-xl shadow-orange-300/30",
      storyBadge: "bg-gradient-to-r from-orange-100 to-red-100 text-orange-950 border-orange-300/60",
      heading: "text-orange-950",
      subtext: "text-orange-800",
      label: "text-orange-700",
      statBg: "bg-[#FFF8F0]/90",
      statDivider: "divide-orange-200",
      hero: "bg-gradient-to-br from-orange-500 via-red-400 to-amber-600",
      cardHidden: "border-orange-300 bg-gradient-to-br from-orange-100 to-amber-200 hover:border-orange-500 hover:-translate-y-1",
      cardRevealed: "border-orange-500 bg-white shadow-lg",
      cardMatched: "bg-green-200 border-green-600",
      tile: "bg-orange-100 border-orange-400 text-orange-950",
      tileActive: "bg-orange-600 text-white",
      dropZone: "border-orange-400 bg-orange-50/50",
      input: "border-orange-400 focus:border-orange-600",
      primaryBtn: "bg-gradient-to-r from-orange-600 to-red-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-orange-500 text-orange-800 bg-[#FFF8F0]",
      progressTrack: "bg-orange-200",
      progressFill: "bg-gradient-to-r from-orange-500 to-red-500",
      statusInfo: "bg-orange-100 text-orange-900",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-orange-400/35",
      menuRing: "ring-orange-400/70",
      topicOverlay: "bg-orange-950/35",
      topicBadge: "border-orange-300/50 bg-[#FFF8F0]/85 text-orange-950",
    },
    ordering: {
      panel: "bg-[#FFF8F0]/92 backdrop-blur-md",
      panelBorder: "border-red-300/70",
      panelShadow: "shadow-xl shadow-red-300/25",
      storyBadge: "bg-gradient-to-r from-red-100 to-amber-100 text-red-950 border-red-300/60",
      heading: "text-red-950",
      subtext: "text-red-800",
      label: "text-red-700",
      statBg: "bg-[#FFF8F0]/90",
      statDivider: "divide-red-200",
      hero: "bg-gradient-to-br from-red-600 via-orange-500 to-amber-700",
      cardHidden: "border-red-300 bg-red-100",
      cardRevealed: "border-red-500 bg-red-50",
      cardMatched: "bg-green-200 border-green-600",
      tile: "bg-red-100 border-red-400 text-red-950 hover:bg-red-200",
      tileActive: "bg-red-700 text-white",
      dropZone: "border-dashed border-red-400 bg-red-50/60",
      input: "border-red-400 focus:border-red-600",
      primaryBtn: "bg-gradient-to-r from-red-600 to-amber-700 hover:shadow-xl",
      secondaryBtn: "border-2 border-red-500 text-red-800 bg-[#FFF8F0]",
      progressTrack: "bg-red-200",
      progressFill: "bg-gradient-to-r from-red-500 to-amber-600",
      statusInfo: "bg-red-100 text-red-900",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-red-400/30",
      menuRing: "ring-red-400/70",
      topicOverlay: "bg-red-950/35",
      topicBadge: "border-red-300/50 bg-[#FFF8F0]/85 text-red-950",
    },
    scramble: {
      panel: "bg-[#FFF8F0]/92 backdrop-blur-md",
      panelBorder: "border-rose-300/70",
      panelShadow: "shadow-xl shadow-rose-300/25",
      storyBadge: "bg-gradient-to-r from-rose-100 to-amber-100 text-rose-950 border-rose-300/60",
      heading: "text-rose-950",
      subtext: "text-rose-800",
      label: "text-rose-700",
      statBg: "bg-[#FFF8F0]/90",
      statDivider: "divide-rose-200",
      hero: "bg-gradient-to-br from-rose-600 via-orange-400 to-amber-600",
      cardHidden: "border-rose-300 bg-rose-100",
      cardRevealed: "border-rose-500 bg-rose-50",
      cardMatched: "bg-green-200 border-green-600",
      tile: "bg-rose-100 border-rose-400 text-rose-950",
      tileActive: "bg-rose-700 text-white",
      dropZone: "border-rose-400 bg-rose-50/50",
      input: "border-rose-400 focus:border-rose-600 focus:ring-rose-200",
      primaryBtn: "bg-gradient-to-r from-rose-600 to-orange-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-rose-500 text-rose-800 bg-[#FFF8F0]",
      progressTrack: "bg-rose-200",
      progressFill: "bg-gradient-to-r from-rose-500 to-orange-500",
      statusInfo: "bg-rose-100 text-rose-900",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-rose-400/30",
      menuRing: "ring-rose-400/70",
      topicOverlay: "bg-rose-950/35",
      topicBadge: "border-rose-300/50 bg-[#FFF8F0]/85 text-rose-950",
    },
    menu: {
      panel: "bg-[#FFF8F0]/88 backdrop-blur-sm",
      panelBorder: "border-amber-300/60",
      panelShadow: "shadow-amber-300/25",
      storyBadge: "bg-amber-100 text-amber-950 border-amber-300",
      heading: "text-amber-950",
      subtext: "text-amber-900",
      label: "text-amber-700",
      statBg: "bg-[#FFF8F0]/85",
      statDivider: "divide-amber-200",
      hero: "bg-gradient-to-br from-amber-200 to-orange-200",
      cardHidden: "",
      cardRevealed: "",
      cardMatched: "",
      tile: "",
      tileActive: "",
      dropZone: "",
      input: "",
      primaryBtn: "",
      secondaryBtn: "",
      progressTrack: "bg-amber-200",
      progressFill: "bg-amber-600",
      statusInfo: "bg-amber-100 text-amber-900",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-amber-400/35",
      menuRing: "ring-amber-400/80",
      topicOverlay: "bg-amber-950/30",
      topicBadge: "border-amber-300 bg-[#FFF8F0]/75",
    },
    topic: {
      panel: "bg-[#FFF8F0]/88 backdrop-blur-sm",
      panelBorder: "border-orange-300/60",
      panelShadow: "shadow-orange-300/25",
      storyBadge: "bg-orange-100 text-orange-950 border-orange-300",
      heading: "text-orange-950",
      subtext: "text-amber-900",
      label: "text-orange-700",
      statBg: "bg-[#FFF8F0]/85",
      statDivider: "divide-orange-200",
      hero: "bg-gradient-to-br from-orange-200 to-amber-200",
      cardHidden: "",
      cardRevealed: "",
      cardMatched: "",
      tile: "",
      tileActive: "",
      dropZone: "",
      input: "",
      primaryBtn: "bg-orange-600 text-white",
      secondaryBtn: "border-orange-500 text-orange-800",
      progressTrack: "bg-orange-200",
      progressFill: "bg-orange-600",
      statusInfo: "bg-orange-100 text-orange-900",
      statusSuccess: "bg-green-100 text-green-800",
      menuOverlay: "shadow-orange-400/35",
      menuRing: "ring-orange-400/80",
      topicOverlay: "bg-orange-950/40",
      topicBadge: "border-amber-300/50 bg-[#FFF8F0]/80 text-orange-950",
    },
  },
  winter: {
    flip: {
      panel: "bg-[#F0F8FF]/93 backdrop-blur-md",
      panelBorder: "border-sky-200/80",
      panelShadow: "shadow-xl shadow-sky-300/35",
      storyBadge: "bg-gradient-to-r from-sky-100 to-indigo-100 text-sky-950 border-sky-200/70",
      heading: "text-sky-950",
      subtext: "text-sky-800",
      label: "text-sky-700",
      statBg: "bg-white/85",
      statDivider: "divide-sky-200",
      hero: "bg-gradient-to-br from-sky-400 via-indigo-400 to-blue-700",
      cardHidden: "border-sky-200 bg-gradient-to-br from-sky-100 via-indigo-100 to-blue-200 hover:border-indigo-300 hover:-translate-y-1 hover:shadow-lg",
      cardRevealed: "border-sky-400 bg-sky-50",
      cardMatched: "bg-teal-200 border-teal-500",
      tile: "bg-sky-100 border-sky-300 text-sky-950",
      tileActive: "bg-indigo-600 text-white",
      dropZone: "border-sky-300 bg-sky-50/60",
      input: "border-sky-300 focus:border-indigo-500 focus:ring-indigo-200",
      primaryBtn: "bg-gradient-to-r from-sky-500 via-indigo-500 to-blue-700 hover:shadow-xl",
      secondaryBtn: "border-2 border-indigo-400 text-indigo-800 bg-[#F0F8FF] hover:bg-sky-50",
      progressTrack: "bg-sky-200",
      progressFill: "bg-gradient-to-r from-sky-400 to-indigo-500",
      statusInfo: "bg-sky-100 text-sky-900",
      statusSuccess: "bg-teal-100 text-teal-800",
      menuOverlay: "shadow-sky-400/40",
      menuRing: "ring-indigo-300/70",
      topicOverlay: "bg-indigo-950/35",
      topicBadge: "border-sky-200/60 bg-[#F0F8FF]/85 text-sky-950",
    },
    speak: {
      panel: "bg-[#F0F8FF]/93 backdrop-blur-md",
      panelBorder: "border-teal-200/80",
      panelShadow: "shadow-xl shadow-teal-300/30",
      storyBadge: "bg-gradient-to-r from-teal-100 to-sky-100 text-teal-950 border-teal-200/70",
      heading: "text-teal-950",
      subtext: "text-teal-800",
      label: "text-teal-700",
      statBg: "bg-white/85",
      statDivider: "divide-teal-200",
      hero: "bg-gradient-to-br from-teal-500 via-cyan-400 to-indigo-600",
      cardHidden: "border-teal-200 bg-teal-100",
      cardRevealed: "border-teal-400 bg-teal-50",
      cardMatched: "bg-teal-200 border-teal-500",
      tile: "bg-teal-100 border-teal-300 text-teal-950",
      tileActive: "bg-teal-700 text-white",
      dropZone: "border-teal-300 bg-teal-50/50",
      input: "border-teal-300 focus:border-teal-600",
      primaryBtn: "bg-gradient-to-r from-teal-600 to-indigo-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-teal-400 text-teal-800 bg-[#F0F8FF]",
      progressTrack: "bg-teal-200",
      progressFill: "bg-gradient-to-r from-teal-400 to-indigo-500",
      statusInfo: "bg-teal-100 text-teal-900",
      statusSuccess: "bg-teal-100 text-teal-800",
      menuOverlay: "shadow-teal-400/35",
      menuRing: "ring-teal-300/70",
      topicOverlay: "bg-teal-950/30",
      topicBadge: "border-teal-200/60 bg-[#F0F8FF]/85 text-teal-950",
    },
    memory: {
      panel: "bg-[#F0F8FF]/93 backdrop-blur-md",
      panelBorder: "border-indigo-200/80",
      panelShadow: "shadow-xl shadow-indigo-300/30",
      storyBadge: "bg-gradient-to-r from-indigo-100 to-amber-100 text-indigo-950 border-indigo-200/70",
      heading: "text-indigo-950",
      subtext: "text-indigo-800",
      label: "text-indigo-700",
      statBg: "bg-white/85",
      statDivider: "divide-indigo-200",
      hero: "bg-gradient-to-br from-indigo-500 via-violet-400 to-amber-500",
      cardHidden: "border-indigo-200 bg-gradient-to-br from-indigo-100 to-sky-200 hover:border-indigo-400 hover:-translate-y-1",
      cardRevealed: "border-indigo-500 bg-white shadow-lg",
      cardMatched: "bg-teal-200 border-teal-500",
      tile: "bg-indigo-100 border-indigo-300 text-indigo-950",
      tileActive: "bg-indigo-600 text-white",
      dropZone: "border-indigo-300 bg-indigo-50/50",
      input: "border-indigo-300 focus:border-indigo-600",
      primaryBtn: "bg-gradient-to-r from-indigo-600 to-violet-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-indigo-400 text-indigo-800 bg-[#F0F8FF]",
      progressTrack: "bg-indigo-200",
      progressFill: "bg-gradient-to-r from-indigo-400 to-violet-500",
      statusInfo: "bg-indigo-100 text-indigo-900",
      statusSuccess: "bg-teal-100 text-teal-800",
      menuOverlay: "shadow-indigo-400/35",
      menuRing: "ring-indigo-300/70",
      topicOverlay: "bg-indigo-950/35",
      topicBadge: "border-indigo-200/60 bg-[#F0F8FF]/85 text-indigo-950",
    },
    ordering: {
      panel: "bg-[#F0F8FF]/93 backdrop-blur-md",
      panelBorder: "border-violet-200/80",
      panelShadow: "shadow-xl shadow-violet-300/25",
      storyBadge: "bg-gradient-to-r from-violet-100 to-sky-100 text-violet-950 border-violet-200/70",
      heading: "text-violet-950",
      subtext: "text-violet-800",
      label: "text-violet-700",
      statBg: "bg-white/85",
      statDivider: "divide-violet-200",
      hero: "bg-gradient-to-br from-violet-600 via-indigo-500 to-sky-600",
      cardHidden: "border-violet-200 bg-violet-100",
      cardRevealed: "border-violet-500 bg-violet-50",
      cardMatched: "bg-teal-200 border-teal-500",
      tile: "bg-violet-100 border-violet-300 text-violet-950 hover:bg-violet-200",
      tileActive: "bg-violet-700 text-white",
      dropZone: "border-dashed border-violet-300 bg-violet-50/60",
      input: "border-violet-300 focus:border-violet-600",
      primaryBtn: "bg-gradient-to-r from-violet-600 to-indigo-700 hover:shadow-xl",
      secondaryBtn: "border-2 border-violet-400 text-violet-800 bg-[#F0F8FF]",
      progressTrack: "bg-violet-200",
      progressFill: "bg-gradient-to-r from-violet-400 to-indigo-500",
      statusInfo: "bg-violet-100 text-violet-900",
      statusSuccess: "bg-teal-100 text-teal-800",
      menuOverlay: "shadow-violet-400/30",
      menuRing: "ring-violet-300/70",
      topicOverlay: "bg-violet-950/35",
      topicBadge: "border-violet-200/60 bg-[#F0F8FF]/85 text-violet-950",
    },
    scramble: {
      panel: "bg-[#F0F8FF]/93 backdrop-blur-md",
      panelBorder: "border-fuchsia-200/80",
      panelShadow: "shadow-xl shadow-fuchsia-300/25",
      storyBadge: "bg-gradient-to-r from-fuchsia-100 to-sky-100 text-fuchsia-950 border-fuchsia-200/70",
      heading: "text-fuchsia-950",
      subtext: "text-fuchsia-800",
      label: "text-fuchsia-700",
      statBg: "bg-white/85",
      statDivider: "divide-fuchsia-200",
      hero: "bg-gradient-to-br from-fuchsia-600 via-violet-400 to-indigo-600",
      cardHidden: "border-fuchsia-200 bg-fuchsia-100",
      cardRevealed: "border-fuchsia-500 bg-fuchsia-50",
      cardMatched: "bg-teal-200 border-teal-500",
      tile: "bg-fuchsia-100 border-fuchsia-300 text-fuchsia-950",
      tileActive: "bg-fuchsia-700 text-white",
      dropZone: "border-fuchsia-300 bg-fuchsia-50/50",
      input: "border-fuchsia-300 focus:border-fuchsia-600 focus:ring-fuchsia-200",
      primaryBtn: "bg-gradient-to-r from-fuchsia-600 to-violet-600 hover:shadow-xl",
      secondaryBtn: "border-2 border-fuchsia-400 text-fuchsia-800 bg-[#F0F8FF]",
      progressTrack: "bg-fuchsia-200",
      progressFill: "bg-gradient-to-r from-fuchsia-400 to-violet-500",
      statusInfo: "bg-fuchsia-100 text-fuchsia-900",
      statusSuccess: "bg-teal-100 text-teal-800",
      menuOverlay: "shadow-fuchsia-400/30",
      menuRing: "ring-fuchsia-300/70",
      topicOverlay: "bg-fuchsia-950/35",
      topicBadge: "border-fuchsia-200/60 bg-[#F0F8FF]/85 text-fuchsia-950",
    },
    menu: {
      panel: "bg-[#F0F8FF]/88 backdrop-blur-sm",
      panelBorder: "border-sky-200/60",
      panelShadow: "shadow-sky-300/30",
      storyBadge: "bg-sky-100 text-sky-950 border-sky-200",
      heading: "text-sky-950",
      subtext: "text-indigo-900",
      label: "text-sky-700",
      statBg: "bg-white/85",
      statDivider: "divide-sky-200",
      hero: "bg-gradient-to-br from-sky-200 to-indigo-200",
      cardHidden: "",
      cardRevealed: "",
      cardMatched: "",
      tile: "",
      tileActive: "",
      dropZone: "",
      input: "",
      primaryBtn: "",
      secondaryBtn: "",
      progressTrack: "bg-sky-200",
      progressFill: "bg-indigo-500",
      statusInfo: "bg-sky-100 text-sky-900",
      statusSuccess: "bg-teal-100 text-teal-800",
      menuOverlay: "shadow-indigo-400/35",
      menuRing: "ring-indigo-300/80",
      topicOverlay: "bg-indigo-950/30",
      topicBadge: "border-sky-200 bg-[#F0F8FF]/75",
    },
    topic: {
      panel: "bg-[#F0F8FF]/88 backdrop-blur-sm",
      panelBorder: "border-indigo-200/60",
      panelShadow: "shadow-indigo-300/30",
      storyBadge: "bg-indigo-100 text-indigo-950 border-indigo-200",
      heading: "text-indigo-950",
      subtext: "text-sky-900",
      label: "text-indigo-700",
      statBg: "bg-white/85",
      statDivider: "divide-indigo-200",
      hero: "bg-gradient-to-br from-indigo-200 to-sky-200",
      cardHidden: "",
      cardRevealed: "",
      cardMatched: "",
      tile: "",
      tileActive: "",
      dropZone: "",
      input: "",
      primaryBtn: "bg-indigo-600 text-white",
      secondaryBtn: "border-indigo-400 text-indigo-800",
      progressTrack: "bg-indigo-200",
      progressFill: "bg-indigo-500",
      statusInfo: "bg-indigo-100 text-indigo-900",
      statusSuccess: "bg-teal-100 text-teal-800",
      menuOverlay: "shadow-indigo-400/35",
      menuRing: "ring-indigo-300/80",
      topicOverlay: "bg-indigo-950/45",
      topicBadge: "border-indigo-200/60 bg-[#F0F8FF]/80 text-indigo-950",
    },
  },
};

export function getGameSeasonTheme(
  season: ForestSeason,
  game: SeasonGameType,
): GameSeasonTheme {
  return {
    ...PALETTES[season][game],
    ...STORIES[season][game],
  };
}
